"""
Django settings for nano_speedtest project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['NANO_ST__SECRET_KEY']

# Key used to access the dPoW service
DPOW_API_KEY = os.environ["NANO_ST__DPOW__API_KEY"]
DPOW_API_USER = os.environ["NANO_ST__DPOW__API_USER"]
DPOW_ENDPOINT = os.environ["NANO_ST__DPOW__ENDPOINT"]
SENDGRID_API_KEY = os.environ["NANO_ST__SENDGRID__API_KEY"]
ADMIN_EMAIL = os.environ["NANO_ST__ADMIN_EMAIL"]
COST_PER_SLOT = os.environ["NANO_ST__COST_PER_SLOT"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admindocs',
    'rest_framework_swagger',
    'corsheaders',
    'speedtest_api',
    'django_crontab',
    'cachalot',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsPostCsrfMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'x_forwarded_for.middleware.XForwardedForMiddleware',
]

CRONTAB_COMMAND_PREFIX = '. $HOME/.bash_profile;'
CRONJOBS = [
    ('0 */1 * * *', 'speedtest_api.clean_up.clean_up'),
    ('17 */3 * * *', 'speedtest_api.cron.node_status_job'),
    ('45 */3 * * *', 'speedtest_api.transaction_test.transaction_test'),
]

CORS_ORIGIN_ALLOW_ALL = True

# CORS_ORIGIN_ALLOW_ALL = False
# CORS_ORIGIN_WHITELIST = (
#     'http//:localhost:8000',
# )

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ["NANO_ST__DB__NAME"],
        'USER': os.environ["NANO_ST__DB__USER"],
        'PASSWORD': os.environ["NANO_ST__DB__PASSWORD"],
        'HOST': os.environ["NANO_ST__DB__HOST"],
        'CONN_MAX_AGE': 15,  # seconds for persistent connection, since Django 1.6
        'OPTIONS': {
                'sql_mode': 'STRICT_ALL_TABLES',
                'ssl': {'ca': os.environ["NANO_ST__DB__SSL__CA__CERT"]},
                'charset': 'utf8mb4',
         }
     }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M',
        },
    },
    'handlers': {
        'application': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'application.log',
            'backupCount': 1, # keep at most 1 log files
            'maxBytes': 52428800, # 50*1024*1024 bytes (50MB)
            'formatter': 'verbose',
        },
        'django': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'django.log',
            'backupCount': 1,  # keep at most 1 log files
            'maxBytes': 52428800,  # 50*1024*1024 bytes (50MB)
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['django'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'speedtest_api': {
            'handlers': ['application'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/root/Nano-SpeedTest/app/backend/static/'
