# Generated by Django 2.1.2 on 2018-10-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionId', models.TextField()),
                ('SenderId', models.TextField()),
                ('ReceiverId', models.TextField()),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('Amount', models.FloatField()),
                ('InitiatorIp', models.TextField()),
            ],
        ),
    ]
