# Generated by Django 2.1.2 on 2018-11-13 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('speedtest_api', '0001_initial'), ('speedtest_api', '0002_wallet_wallet_id'), ('speedtest_api', '0003_auto_20181031_1639'), ('speedtest_api', '0004_auto_20181031_2117'), ('speedtest_api', '0005_auto_20181031_2242'), ('speedtest_api', '0006_auto_20181031_2245'), ('speedtest_api', '0007_auto_20181031_2247'), ('speedtest_api', '0008_auto_20181031_2320'), ('speedtest_api', '0009_auto_20181101_0228'), ('speedtest_api', '0010_node_location_name'), ('speedtest_api', '0002_auto_20181101_0014'), ('speedtest_api', '0011_merge_20181101_2140'), ('speedtest_api', '0012_auto_20181101_2140'), ('speedtest_api', '0013_node_enabled'), ('speedtest_api', '0014_auto_20181113_0016'), ('speedtest_api', '0015_auto_20181113_0017'), ('speedtest_api', '0016_auto_20181113_0021'), ('speedtest_api', '0017_auto_20181113_0033')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64)),
                ('current_balance', models.IntegerField()),
                ('POW', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.GenericIPAddressField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_send_timestamp', models.BigIntegerField(default=None, null=True)),
                ('end_send_timestamp', models.BigIntegerField(default=None, null=True)),
                ('start_receive_timestamp', models.BigIntegerField(default=None, null=True)),
                ('end_receive_timestamp', models.BigIntegerField(default=None, null=True)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=38)),
                ('initiated_by', models.GenericIPAddressField()),
                ('transaction_hash_sending', models.CharField(max_length=64)),
                ('transaction_hash_receiving', models.CharField(max_length=64)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='speedtest_api.Account')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='speedtest_api.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speedtest_api.Node')),
                ('wallet_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speedtest_api.Wallet'),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=38),
        ),
        migrations.AlterField(
            model_name='account',
            name='POW',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='location_name',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='node',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.RenameField(
            model_name='node',
            old_name='IP',
            new_name='URL',
        ),
        migrations.AlterField(
            model_name='node',
            name='URL',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='node',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='node',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
