# Generated by Django 2.1.2 on 2018-11-14 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_api', '0001_squashed_0017_auto_20181113_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated_by', models.GenericIPAddressField()),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='initiated_by',
        ),
        migrations.AddField(
            model_name='transaction',
            name='batch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='speedtest_api.Batch'),
            preserve_default=False,
        ),
    ]
