# Generated by Django 2.1.2 on 2018-10-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(default=None, max_length=39),
            preserve_default=False,
        ),
    ]
