# Generated by Django 2.1.1 on 2018-10-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_hash',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
