# Generated by Django 2.1.2 on 2018-10-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_hash_receiving',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_hash_sending',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(default=None, max_length=39),
            preserve_default=False,
        ),
    ]
