# Generated by Django 2.1.2 on 2018-11-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_api', '0002_auto_20181113_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('title', models.TextField()),
                ('start_timestamp', models.BigIntegerField(default=None, null=True)),
                ('end_timestamp', models.BigIntegerField(default=None, null=True)),
                ('company', models.TextField()),
                ('tokens', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
