# Generated by Django 2.1.1 on 2018-10-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_api', '0002_transaction_transaction_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_hash',
            new_name='transaction_hash_receiving',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_hash_sending',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
