# Generated by Django 2.1.1 on 2018-10-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_api', '0003_auto_20181030_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
