# Generated by Django 2.1.2 on 2018-11-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_api', '0003_auto_20181031_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.IntegerField(default=0),
        ),
    ]
