# Generated by Django 2.1.2 on 2018-10-30 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_api', '0004_account_address'),
        ('speedtest_api', '0002_auto_20181030_2129'),
    ]

    operations = [
    ]
