# Generated by Django 2.1.2 on 2018-11-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_api', '0004_auto_20181031_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
