# Generated by Django 2.1.2 on 2018-11-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_api', '0005_auto_20181031_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=25),
        ),
    ]
