# Generated by Django 2.1.2 on 2018-11-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_api', '0008_auto_20181031_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='POW',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
