# Generated by Django 2.1.2 on 2018-11-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_api', '0009_auto_20181101_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='location_name',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
