# Generated by Django 2.1.2 on 2018-11-02 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_api', '0002_auto_20181101_0014'),
        ('speedtest_api', '0010_node_location_name'),
    ]

    operations = [
    ]
