# Generated by Django 2.1.2 on 2018-11-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_api', '0011_merge_20181101_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='end_receive_timestamp',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='end_send_timestamp',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='start_receive_timestamp',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='start_send_timestamp',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
