# Generated by Django 2.1.2 on 2018-11-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_api', '0012_auto_20181101_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
