# Generated by Django 2.1.2 on 2018-11-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_api', '0013_node_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='IP',
            field=models.CharField(max_length=512),
        ),
    ]
