# Generated by Django 2.1.2 on 2018-11-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_api', '0014_auto_20181113_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='IP',
            new_name='address',
        ),
    ]
