# Generated by Django 2.1.2 on 2018-11-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_api', '0015_auto_20181113_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='address',
            new_name='URL',
        ),
    ]
