# Generated by Django 2.1.2 on 2018-11-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest_api', '0016_auto_20181113_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='node',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
